# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://www.specoding.com/"  # Include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright Â© 2025, Tony Kay and the Hugo Authors; all rights reserved."
# canonifyurls = true

theme = "hugo-clarity"
disqusShortname = "www-speccoding-com"

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
  pagerSize = 10
